import { v4 } from 'uuid';

export default [
  {
    id: v4(),
    name: 'New Apple iPhone 11 (64GB)',
    image: 'https://m.media-amazon.com/images/I/71tpxtLD0aL._AC_AA180_.jpg',
    price: 50999,
    discount: 3,
    stars: 4.5,
    numReviews: 6576,
    deliveryDays: 6,
    fullfilled: true,
    keywords: ['mobile', 'iphone', 'apple'],
  },
  {
    id: v4(),
    name: 'iQOO 7 Legend 5G (Legendary Track Design, 8GB RAM, 128GB Storage) | 3GB Extended RAM | Upto 12 Months No Cost EMI | 6 Months Free Screen Replacement',
    image:
      'https://images-eu.ssl-images-amazon.com/images/I/31LBYv2eEbS._SX300_SY300_QL70_FMwebp_.jpg',
    price: 39990, // in rupees
    discount: 11, // in percent
    stars: 4.4,
    numReviews: 2444,
    deliveryDays: 6,
    fullfilled: true,
    keywords: ['mobile', 'legend', 'iQOO'],
  },
  {
    id: v4(),
    name: 'New Apple iPhone 12 Pro Max (128GB) - Pacific Blue',
    image:
      'https://images-eu.ssl-images-amazon.com/images/I/41N9-hbLe0L._SY445_SX342_QL70_FMwebp_.jpg',
    price: 124700,
    discount: 4,
    stars: 4.6,
    numReviews: 4687,
    deliveryDays: 6,
    fullfilled: true,
    keywords: ['mobile', 'apple', 'iphone'],
  },
  {
    id: v4(),
    name: 'Samsung Galaxy Z Fold2 5G Mystic Bronze, 12GB RAM, 256GB Storage',
    image:
      'https://images-eu.ssl-images-amazon.com/images/I/41pBRVVBk5L._SX300_SY300_QL70_FMwebp_.jpg',
    price: 134999,
    discount: 29,
    stars: 4.6,
    numReviews: 94,
    deliveryDays: 6,
    fullfilled: false,
    keywords: ['mobile', 'samsung', 'galaxy', 'fold'],
  },
  {
    id: v4(),
    name: 'Mi 11X 5G Cosmic Black 6GB RAM 128GB ROM | SD 870 | DisplayMate A+ rated E4 AMOLED',
    image:
      'https://images-eu.ssl-images-amazon.com/images/I/41vVavfyzxS._SX300_SY300_QL70_FMwebp_.jpg',
    price: 29999,
    discount: 12,
    stars: 4,
    numReviews: 3569,
    deliveryDays: 6,
    fullfilled: true,
    keywords: ['mobile', 'mi', 'xiaomi'],
  },
  {
    id: v4(),
    name: 'Redmi 9A (Nature Green, 2GB RAM, 32GB Storage) | 2GHz Octa-core Helio G25 Processor | 5000 mAh Battery',
    image:
      'https://images-eu.ssl-images-amazon.com/images/I/41jRzGyDUJL._SX300_SY300_QL70_FMwebp_.jpg',
    price: 6999,
    discount: 18,
    stars: 4.2,
    numReviews: 70926,
    deliveryDays: 6,
    fullfilled: true,
    keywords: ['mobile', 'redmi', 'xiaomi'],
  },
  {
    id: v4(),
    name: 'OPPO F19 Pro+ 5G(Space Silver, 8GB RAM, 128GB Storage) with No Cost EMI / Additional Exchange OffersOPPO F19 Pro + 5G(Space Silver, 8GB RAM, 128GB Storage) with No Cost EMI / Additional Exchange Offers',
    image:
      'https://images-eu.ssl-images-amazon.com/images/I/413B3aiSBdL._SX300_SY300_QL70_FMwebp_.jpg',
    price: 25990,
    discount: 13,
    stars: 4.1,
    numReviews: 2463,
    deliveryDays: 6,
    fullfilled: true,
    keywords: ['mobile', 'oppo', 'f19'],
  },
  {
    id: v4(),
    name: 'Samsung Galaxy M42 5G(Prism Dot Gray, 8GB RAM, 128GB Storage)Samsung Galaxy M42 5G(Prism Dot Gray, 8GB RAM, 128GB Storage)',
    image:
      'https://images-eu.ssl-images-amazon.com/images/I/41znff7SgPL._SX300_SY300_QL70_FMwebp_.jpg',
    price: 23999,
    discount: 20,
    stars: 4.1,
    numReviews: 6367,
    deliveryDays: 6,
    fullfilled: true,
    keywords: ['mobile', 'samsung', 'galaxy', 'm42'],
  },
  {
    id: v4(),
    name: 'OnePlus 9 Pro 5G (Stellar Black, 8GB RAM, 128GB Storage) I Extra upto Rs.7000 off on ExchangeOnePlus 9 Pro 5G (Stellar Black, 8GB RAM, 128GB Storage) I Extra upto Rs.7000 off on Exchange',
    image:
      'https://images-eu.ssl-images-amazon.com/images/I/41KqaHvwcpL._SX300_SY300_QL70_FMwebp_.jpg',
    price: 64999,
    discount: 0,
    stars: 4.2,
    numReviews: 3871,
    deliveryDays: 6,
    fullfilled: true,
    keywords: ['oneplus', 'pro', 'mobile'],
  },
];
